Proyecto31095/Dm/urls.py
from django.urls import path, re_path

from .views import (

	mensajes_privados,
	DetailMs,
	CanalDetailView,
	Inbox
	

)

UUID_CANAL_REGEX = r'canal/(?P<pk>[a-f0-9]{8}-?[a-f0-9]{4}-?4[a-f0-9]{3}-?[89ab][a-f0-9]{3}-?[a-f0-9]{12})'

urlpatterns=[
	
	re_path(UUID_CANAL_REGEX, CanalDetailView.as_view()),
	path("dm/<str:username>", mensajes_privados, name='DmUser'),
	path("ms/<str:username>", DetailMs.as_view(), name="detailms"),

	path("", Inbox.as_view(), name="inbox"),

]

Proyecto31095/Proyecto31095/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect

from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', lambda req: redirect('AppCoderInicio')),
    path('admin/', admin.site.urls),
    path('AppCoder/', include('AppCoder.urls')),
    path('UserCoder/', include('UserCoder.urls')),
    path('Chat/', include('Dm.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Proyecto31095/Dm/models.py
from django.db import models
from django.conf import settings
import uuid

from django.apps import apps

from django.db.models import Count

User = settings.AUTH_USER_MODEL

class ModelBase(models.Model):
    # uuid.uuid4
	id = models.UUIDField(default=uuid.uuid4, primary_key=True, db_index=True, editable=False)
	tiempo = models.DateTimeField(auto_now_add=True)
	actualizar = models.DateTimeField(auto_now=True)

	class Meta:
		abstract = True


class CanalMensaje(ModelBase):
	canal   = models.ForeignKey("Canal", on_delete=models.CASCADE)
	usuario = models.ForeignKey(User, on_delete=models.CASCADE)
	texto =  models.TextField()

class CanalUsuario(ModelBase):
	canal  = models.ForeignKey("Canal", null=True, on_delete=models.SET_NULL)
	usuario = models.ForeignKey(User, on_delete=models.CASCADE)


class CanalQuerySet(models.QuerySet):

	def solo_uno(self):
		return self.annotate(num_usuarios=Count("usuarios")).filter(num_usuarios=1)

	def solo_dos(self):
		return self.annotate(num_usuarios= Count("usuarios")).filter(num_usuarios=2)

	def filtrar_por_username(self, username):
		return self.filter(canalusuario__usuario__username=username)


class CanalManager(models.Manager):
	
	def get_queryset(self, *args, **kwargs):
		return CanalQuerySet(self.model, using=self._db)

	def filtrar_ms_por_privado(self, username_a, username_b):
		return self.get_queryset().solo_dos().filtrar_por_username(username_a).filtrar_por_username(username_b)

	def obtener_o_crear_canal_usuario_actual(self, user):
		qs = self.get_queryset().solo_uno().filtrar_por_username(user.username)
		if qs.exists():
			return qs.order_by("tiempo").first, False

		canal_obj = Canal.objects.create()
		CanalUsuario.objects.create(usuario=user, canal=canal_obj)
		return canal_obj, True

	def obtener_o_crear_canal_ms(self, username_a, username_b):
		qs = self.filtrar_ms_por_privado(username_a, username_b)
		if qs.exists():

			return qs.order_by("tiempo").first(), False #obj, created

		User = apps.get_model("auth", model_name='User')
		usuario_a, usuario_b = None, None
		try:
			usuario_a = User.objects.get(username=username_a)
		except User.DoesNotExist:
			return None, False

		try:
			usuario_b = User.objects.get(username=username_b)
		except User.DoesNotExist:
			return None, False

		if usuario_a == None or usuario_b==None:
			return None, False

		
		obj_canal =Canal.objects.create()
		canal_usuario_a = CanalUsuario(usuario=usuario_a, canal=obj_canal)
		canal_usuario_b = CanalUsuario(usuario=usuario_b, canal=obj_canal)
		CanalUsuario.objects.bulk_create([canal_usuario_a, canal_usuario_b])
		return obj_canal, True

class Canal(ModelBase):
	#como funciona slak
	#1 user
	#2 users
	#2+

	usuarios = models.ManyToManyField(User, blank=True, through=CanalUsuario)

	objects = CanalManager()

Proyecto31095/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	{% load static %}
	<title>CHAT</title>
	<style>
		@import url('https://fonts.googleapis.com/css2?family=Roboto&display=swap');

		*{
			margin: 0;
			padding: 0;
		}

		body{
			background:#fafafa;
		}

		h1, h2, h3, p, small{
			font-family: 'Roboto', sans-serif;
		}

		.div_main{
			width: 60%;
			margin: 50px auto;
		}

	</style>
	<link href=" {% static 'css/styles.css' %} " rel="stylesheet" />
</head>
<body>
	{% include 'sections/navBar.html' %}
	<div class="div_main">
		{% block contenedor %}
		
		{% endblock %}
	</div>
	{% include 'sections/footer.html' %}
</body>
</html>

Proyecto31095/templates/base_formulario.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{{ titulo_form }}{% endblock %}</title>
    <link href=" {% static 'css/styles.css' %} " rel="stylesheet" />
</head>
<body>
    {% include 'sections/navBar.html' %}
    
    {% block inicio %}
        <h1 class="text-primary" style="margin: 2em auto 1em auto; width:fit-content">COMPLETE EL FORMULARIO</h1>
        <h2>{{ titulo_form }}</h2>
        <br>
        <div style="width: 80%; height: min-content; margin: 1em auto 1em auto;" class="container justify-content-center p-2 shadow-lg border rounded bg-primary bg-opacity-75 text-white">
        <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
    
            {{ form.as_p }}
    
            <input type="submit" value="{{ boton_envio }}">
    
        </form>
        <br>
        <hr>
            <a style="display: flex; width: min-content;" class="nav-link text-white bg-info" href="{% url 'UserCoderAvatar' %}">AGREGAR AVATAR</a>
        </div>
        {% endblock %}
        <br>
        <br>
        <br>
    {% include 'sections/footer.html' %}    
</body>
</html>

Proyecto31095/templates/inbox.html
{% extends 'base.html' %}


{% block contenedor %}
<div>
<h1 style="color: #3b48ff; width: max-content; margin: auto;"> BIENVENIDO {{user}} A TU CASILLA DE MENSAJES </h1>

{% for inbox in inbox %}
<div style="margin:5em; background: #fff; border-radius: 5px; border:1px solid #e6e6e6; padding: 5px;">
	
	{% for second_user in inbox.canalusuario_set.all %}

		{% if second_user.usuario ==  request.user %}

		{% else %}

			<a href="{% url 'detailms' second_user.usuario.username %}">
				<p>	{{second_user.usuario}}	</p>
				<small>	({{inbox.canalmensaje_set.count}}) Mensajes</small>
			</a>

		{% endif %}

	{% endfor %}

	{% if inbox.canalmensaje_set.count != 0 %}
		<div class="div_ms_inbox">
			{% with ultimo_mensaje=inbox.canalmensaje_set.last %}

				<p> Mensaje: {{ultimo_mensaje.texto}}</p>

				<p>Usuario: {{ultimo_mensaje.usuario}}</p>
			{% endwith %}
		</div>	
	{% else %}
		<p>	No hay mensajes en nuestro inbox </p>
	{% endif %}



</div>
{% empty %}
	<div style="padding: 1em ;margin: 10em auto 10em auto; background-color: aliceblue; display: flex; border: gray solid 2px; border-radius: 10px;">
		<h2 class="text-primary" style="width: max-content; text-align: center; margin: auto;"> SU INBOX SE ENCUENTRA VACÍO </h2>
	</div>
	<a class="btn btn-primary" href="{% url 'AppCoderInicio' %}">VOLVER A LA PÁGINA PRINCIPAL</a>
{% endfor %}

</div>

		
{% endblock %}

Proyecto31095/templates/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title> {% block title %} INICIO {% endblock %}</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href=" {% static 'css/styles.css' %} " rel="stylesheet" />
    </head>
    <body>
        {% include 'sections/navBar.html' %}
        <header class="m-4 p-4">
        
        {% block inicio %}
        {% endblock %}
        {% block login %}
        {% endblock %}
        {% block numero %}
        {% endblock %}
        <h1 class="text-primary text-center">ENCONTRÁ TODO SOBRE PROGRAMACIÓN Y DESARROLLO</h1>
        <br>
        </header>

        <!-- Page content-->
        <div class="row ">
            <div class="col-lg-8 p-4 bg-primary bg-opacity-25">
                {% block blogs %}
                {% for blog in posts %}
                <div class="col-lg-12">
                    <!-- Blog post-->
                    <div class="card mb-4">
                        <img class="card-img-top" src="https://www.michaelpage.es/sites/michaelpage.es/files/styles/advice_node_desktop/public/2021-11/Full%20Stack%20Developer.jpg?itok=mciNzA6q" alt="foto" />
                        <div class="card-body">
                        <h1>{{blog.title}}</h1>
                        <h2 class="card-title h4">{{blog.subtitle}}</h2>
                        <p class="card-text">Autor/a: {{blog.author}}</p>
                        <p class="card-text">{{blog.post_date}}</p>
                        <a class="btn btn-primary" href="{% url 'AppCoderDetalles' blog.title %}">LEER MÁS →</a>
                    </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            {% endblock %}
            <div class="col-lg-4 ">
                <div class="card-mb-4 border border-primary bg-success bg-opacity-25">
                    <div class="card-header">
                        <img class="card-img-top" src="https://spicyminds.mx/wp-content/uploads/2019/04/busqueda.png" alt="busqueda" />
                    </div>
                    <div class="card-body">
                        <p>Puedes ubicar posts por el título</p>
                        <a href="{% url 'AppCoderBusquedaBlog' %}">ENCUENTRA EL POST</a>
                    </div>
                </div>
            </div>

        </div>


        {% include 'sections/footer.html' %}
        
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>