Proyecto31095/Dm/urls.py
from django.urls import path, re_path

from .views import (

	mensajes_privados,
	DetailMs,
	CanalDetailView,
	Inbox
	

)

UUID_CANAL_REGEX = r'canal/(?P<pk>[a-f0-9]{8}-?[a-f0-9]{4}-?4[a-f0-9]{3}-?[89ab][a-f0-9]{3}-?[a-f0-9]{12})'

urlpatterns=[
	
	re_path(UUID_CANAL_REGEX, CanalDetailView.as_view()),
	path("dm/<str:username>", mensajes_privados, name='DmUser'),
	path("ms/<str:username>", DetailMs.as_view(), name="detailms"),

	path("", Inbox.as_view(), name="inbox"),

]

Proyecto31095/Proyecto31095/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect

from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', lambda req: redirect('AppCoderInicio')),
    path('admin/', admin.site.urls),
    path('AppCoder/', include('AppCoder.urls')),
    path('UserCoder/', include('UserCoder.urls')),
    path('Chat/', include('Dm.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Proyecto31095/Dm/models.py
from django.db import models
from django.conf import settings
import uuid

from django.apps import apps

from django.db.models import Count

User = settings.AUTH_USER_MODEL

class ModelBase(models.Model):
    # uuid.uuid4
	id = models.UUIDField(default=uuid.uuid4, primary_key=True, db_index=True, editable=False)
	tiempo = models.DateTimeField(auto_now_add=True)
	actualizar = models.DateTimeField(auto_now=True)

	class Meta:
		abstract = True


class CanalMensaje(ModelBase):
	canal   = models.ForeignKey("Canal", on_delete=models.CASCADE)
	usuario = models.ForeignKey(User, on_delete=models.CASCADE)
	texto =  models.TextField()

class CanalUsuario(ModelBase):
	canal  = models.ForeignKey("Canal", null=True, on_delete=models.SET_NULL)
	usuario = models.ForeignKey(User, on_delete=models.CASCADE)


class CanalQuerySet(models.QuerySet):

	def solo_uno(self):
		return self.annotate(num_usuarios=Count("usuarios")).filter(num_usuarios=1)

	def solo_dos(self):
		return self.annotate(num_usuarios= Count("usuarios")).filter(num_usuarios=2)

	def filtrar_por_username(self, username):
		return self.filter(canalusuario__usuario__username=username)


class CanalManager(models.Manager):
	
	def get_queryset(self, *args, **kwargs):
		return CanalQuerySet(self.model, using=self._db)

	def filtrar_ms_por_privado(self, username_a, username_b):
		return self.get_queryset().solo_dos().filtrar_por_username(username_a).filtrar_por_username(username_b)

	def obtener_o_crear_canal_usuario_actual(self, user):
		qs = self.get_queryset().solo_uno().filtrar_por_username(user.username)
		if qs.exists():
			return qs.order_by("tiempo").first, False

		canal_obj = Canal.objects.create()
		CanalUsuario.objects.create(usuario=user, canal=canal_obj)
		return canal_obj, True

	def obtener_o_crear_canal_ms(self, username_a, username_b):
		qs = self.filtrar_ms_por_privado(username_a, username_b)
		if qs.exists():

			return qs.order_by("tiempo").first(), False #obj, created

		User = apps.get_model("auth", model_name='User')
		usuario_a, usuario_b = None, None
		try:
			usuario_a = User.objects.get(username=username_a)
		except User.DoesNotExist:
			return None, False

		try:
			usuario_b = User.objects.get(username=username_b)
		except User.DoesNotExist:
			return None, False

		if usuario_a == None or usuario_b==None:
			return None, False

		
		obj_canal =Canal.objects.create()
		canal_usuario_a = CanalUsuario(usuario=usuario_a, canal=obj_canal)
		canal_usuario_b = CanalUsuario(usuario=usuario_b, canal=obj_canal)
		CanalUsuario.objects.bulk_create([canal_usuario_a, canal_usuario_b])
		return obj_canal, True

class Canal(ModelBase):
	#como funciona slak
	#1 user
	#2 users
	#2+

	usuarios = models.ManyToManyField(User, blank=True, through=CanalUsuario)

	objects = CanalManager()

Proyecto31095/Dm/forms.py
from django import forms

class FormMensajes(forms.Form):
	mensaje = forms.CharField(widget=forms.Textarea(attrs = {

			"class": "formulario_ms",
			"placeholder":"Escribe tu mensaje"

		}))

Proyecto31095/Dm/views.py
from django.shortcuts import render
from django.views.generic import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from .models import CanalMensaje, CanalUsuario, Canal
from django.http import HttpResponse, Http404, JsonResponse

from .forms import FormMensajes

from django.views.generic.edit import FormMixin

from django.views.generic import View

class Inbox(View):
	def get(self, request):

		inbox = Canal.objects.filter(canalusuario__usuario__in=[request.user.id])

		context = {
			"inbox":inbox
		}

		return render(request, 'inbox.html', context)


class CanalFormMixin(FormMixin):
	form_class =FormMensajes

	def get_success_url(self):
		return self.request.path

	def post(self, request, *args, **kwargs):

		if not request.user.is_authenticated:
			raise PermissionDenied

		form = self.get_form()
		if form.is_valid():
			canal = self.get_object()
			usuario = self.request.user 
			mensaje = form.cleaned_data.get("mensaje")
			canal_obj = CanalMensaje.objects.create(canal=canal, usuario=usuario, texto=mensaje)
			
			if request.is_ajax():
				return JsonResponse({

					'mensaje':canal_obj.texto,
					'username':canal_obj.usuario.username
					}, status=201)

			return super().form_valid(form)

		else:

			if request.is_ajax():
				return JsonResponse({"Error":form.errors}, status=400)

			return super().form_invalid(form)

class CanalDetailView(LoginRequiredMixin, CanalFormMixin, DetailView):
	template_name= 'Dm/canal_detail.html'
	queryset = Canal.objects.all()

	def get_context_data(self, *args, **kwargs):
		context = super().get_context_data(*args, **kwargs)

		obj = context['object']
		print(obj)

		context['si_canal_mienbro'] = self.request.user in obj.usuarios.all()

		return context



class DetailMs(LoginRequiredMixin, CanalFormMixin, DetailView):

	template_name= 'Dm/canal_detail.html'

	def get_object(self, *args, **kwargs):

		username = self.kwargs.get("username")
		mi_username = self.request.user.username
		canal, _ = Canal.objects.obtener_o_crear_canal_ms(mi_username, username)

		if username == mi_username:
			mi_canal, _ = Canal.objects.obtener_o_crear_canal_usuario_actual(self.request.user)

			return mi_canal

		if canal == None:
			raise Http404

		return canal

def mensajes_privados(request, username, *args, **kwargs):

	if not request.user.is_authenticated:
		return HttpResponse("Prohibido")

	mi_username = request.user.username

	canal, created = Canal.objects.obtener_o_crear_canal_ms(mi_username, username)

	if created:
		print("Si, fue creado")

	Usuarios_Canal = canal.canalusuario_set.all().values("usuario__username")
	print(Usuarios_Canal)
	mensaje_canal  = canal.canalmensaje_set.all()
	print(mensaje_canal.values("texto"))

	return HttpResponse(f"Nuestro Id del Canal - {canal.id}")

Proyecto31095/templates/Dm/canal_detail.html
{% extends 'base.html' %}

{% block contenedor %}
	
	<style>
		#titulo{
			margin:auto;
			color: #1d44f2;
			width: fit-content;
			padding: 10px;
			display: flex;
		}
		#identificador{
			background-color: aliceblue;
			width: fit-content;
			margin:auto;
			padding: 10px;
			display: flex;
		}
		#contenedor_ms{
			width: 100%;
			height: calc(70vh);
			padding: 1em;
			margin: 5px 0;
			overflow-y: auto;
			border-bottom: 1px solid #e6e6e6;
			background: #a8dfff;
		}

		.div_ms{
			margin: 1.2rem auto;
			width: 35%;
			padding: 0.2rem 0.6rem 02rem 0.6rem;

		}
		.mis_mensajes{
			margin-right: 5px;
			background-color:#1da1f2;
			color: #fff;
			border-bottom-left-radius: 16px;
			border-top-left-radius: 16px;
			border-top-right-radius: 16px;
		}

		.tus_mensajes{
			background: rgb(230, 236, 240);
			margin-left: 5px;
			border-bottom-right-radius: 16px;
			border-top-left-radius: 16px;
			border-top-right-radius: 16px;

		}

		.div_form_ms{
			width: 100%;
			margin-top: 5px;
			margin-bottom: 5px;
			margin-left: -3px;
			border:1px solid #e6e6e6;
			background-color: aliceblue;
		}

		#id_mensaje{
			display: block;
			padding: 6px 12px;
			margin-left: 1%;
			margin-right: 1%;
			width: 98%;
			min-width: 98%;
			max-width: 98%;
			height: 70px;
			min-height: 70px;
			max-height: 70px;
			box-sizing: border-box;
			font-size: 14px;
			color: #333;
			border:1px solid #ccc;
			border-radius: 4px;

		}

		.btn_enviar{
			background: #98ca3f;
			color: #fff;
			padding: 5px 10px;
			border-radius: 5px;
			border:none;
			outline: none;
			border-bottom: 5px solid #6d932b;
			width: 150px;
			cursor: pointer;
			display: block;
			margin: 10px auto;
			font-size: 13px;
			transition: 0.3;
			
		}

	</style>


	<h3 id="identificador">Identificador del canal: {{object.id}}</h3>

	<h1 id="titulo" >Mensajes del canal</h1>

	<div id="contenedor_ms">
	{% for mensaje in object.canalmensaje_set.all %}	
		<div class="div_ms {% if request.user == mensaje.usuario %}mis_mensajes
		{% else %} tus_mensajes{% endif %}">
			<small>{{mensaje.usuario}}</small>
			<p>{{mensaje.texto}}</p>
			<small>{{mensaje.tiempo}}</small>
		</div>

	{% endfor %}
	</div>
	<div class="div_form_ms">
		<form id="form_submit" action="{{ request.path }}" method="POST">
			{% csrf_token %}

			{{form.as_p}}

			<button type="submit" class="btn_enviar">
				Enviar
			</button>

	</form>

	</div>

<script>

	const MsgForm = document.getElementById("form_submit")
	const msgContainer = document.getElementById("contenedor_ms")


	MsgForm.addEventListener("submit", (event) => {

		event.preventDefault()

		const  targetDate = event.target 
		const formData = new FormData(targetDate)

		const xhr = new XMLHttpRequest() // ajax fetch


		const endpoint = MsgForm.getAttribute("action")
		const method = MsgForm.getAttribute("method")
		xhr.open(method, endpoint)

		xhr.responseType = 'json'

		xhr.setRequestHeader("HTTP_X_REQUESTED_WITH", "XMLHttpRequest")
		xhr.setRequestHeader("X-Requested-With", "XMLHttpRequest")

		xhr.onload = () =>{

			console.log(xhr.status, xhr.response)

			if(xhr.status === 201){
				const respuestaData = xhr.response
				let actualMensajeHtml = msgContainer.innerHTML
				actualMensajeHtml += `<div class=''><b>${respuestaData.username}</b><p>${respuestaData.mensaje}</p></div>` 
				msgContainer.innerHTML = actualMensajeHtml
				MsgForm.reset()
			}else if(xhr.status === 400){
				console.log(hxr.response)
			}else{
				window.location.reload()
			}

		}

		xhr.send(formData)


	})
	


</script>

{% endblock %}